export const submissionWordList = [
    'abomination',
    'all powerful',
    'almighty',
    'ambition',
    'atone',
    'authority',
    'beg',
    'beseech',
    'bow down',
    'conceit',
    'condemn',
    'conduct',
    'confess',
    'creator',
    'decree',
    'defile',
    'displease',
    'fear god',
    'flock',
    'forgive',
    'go unto',
    'grovel',
    'heavenly father',
    'holy father',
    'humble',
    'humility',
    'inferior',
    'iniquity',
    'jealous god',
    'judgement',
    'kneel',
    'let her',
    'let him',
    'lord',
    'lowly',
    'mercy',
    'mighty',
    'not worthy',
    'obedient',
    'obey',
    'offereth',
    'offering',
    'plead',
    'praise',
    'priest shall',
    'profane',
    'punish',
    'rebel',
    'remain silent',
    'reverence',
    'rule over',
    'sackcloth',
    'sacrifice',
    'sanctify',
    'servant',
    'serve',
    'shall',
    'shalt',
    'sheep',
    'shepherd',
    'sin',
    'subject',
    'submit',
    'subordinate',
    'supplicant',
    'thou shalt',
    'thou shalt not',
    'transgress',
    'trembling',
    'trespass',
    'trespass',
    'unclean',
    'unclean',
    'vanity',
    'wicked',
    'wicked',
    'worm',
    'worship',
    'yield',
];
